apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          #image: 172.16.142.25:5000/myapp:latest
          image: 172.16.142.25:5000/myapp:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
