apiVersion: v1
kind: Service
metadata:
  name: my-app-lb
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - name: "http-myapplb"
    port: 28080
    targetPort: 8080
  selector:
    app: myapp
